### ISSUE TITLE
UI-Layout "skizzieren"

### ISSUE THREAD

**Issue by nickodei** [nickodei/Das-Social-Network#4]
Es soll eine Skizze über das initiale Layout geben. 

Sinn ist es, sich mit der UI auseinander zu setzen

**Comment by florianfoerg** [comment]
Skizzen initiales Layout: 

![Hauptseite Social Network Skizze Frontend](https://user-images.githubusercontent.com/65611876/170271245-8d9f8b1e-f4a9-4396-8e9b-3bd4dfa0f8c8.png)
![Restaurant Page Seite](https://user-images.githubusercontent.com/65611876/170271255-eeae4282-d68c-478c-929a-eabe12ddf2f8.png)
